import type { MaterialPreset, ParameterMeta } from '../../types'

export const MATERIAL_PRESETS: MaterialPreset[] = [
  {
    key: 'Ti-6Al-4V',
    label: 'Ti-6Al-4V',
    description: 'Titanium alloy · aerospace & medical',
    conductivity: 6.7,
    diffusivity: 2.9,
    liquidus: 1655,
    absorptivity: 0.35,
  },
  {
    key: '316L',
    label: '316L Stainless Steel',
    description: 'Austenitic steel · corrosion resistance',
    conductivity: 14.6,
    diffusivity: 3.9,
    liquidus: 1400,
    absorptivity: 0.35,
  },
  {
    key: 'IN718',
    label: 'IN718 (Inconel)',
    description: 'Nickel superalloy · high temperature',
    conductivity: 11.4,
    diffusivity: 3.1,
    liquidus: 1336,
    absorptivity: 0.30,
  },
  {
    key: 'AlSi10Mg',
    label: 'AlSi10Mg',
    description: 'Aluminum alloy · lightweight',
    conductivity: 147.0,
    diffusivity: 64.2,
    liquidus: 596,
    absorptivity: 0.15,
  },
  {
    key: 'CoCrMo',
    label: 'CoCrMo',
    description: 'Cobalt-chromium · biomedical implants',
    conductivity: 13.0,
    diffusivity: 3.5,
    liquidus: 1350,
    absorptivity: 0.35,
  },
  {
    key: 'Custom',
    label: 'Custom',
    description: 'Manually set all parameters',
    conductivity: 18,
    diffusivity: 5.2,
    liquidus: 1650,
    absorptivity: 0.35,
  },
]

export const PARAMETER_META: ParameterMeta[] = [
  {
    key: 'power',
    label: 'Laser Power',
    symbol: 'P',
    unit: 'W',
    min: 50,
    max: 500,
    step: 5,
    defaultValue: 200,
    tooltip:
      'Energy delivered by the laser per second. Higher power melts more material but can cause keyholing or excessive vaporization. Typical LPBF range: 50–500 W.',
  },
  {
    key: 'speed',
    label: 'Scan Speed',
    symbol: 'v',
    unit: 'mm/s',
    min: 100,
    max: 2000,
    step: 10,
    defaultValue: 800,
    tooltip:
      'How fast the laser moves across the powder bed. Faster speeds reduce heat input, creating smaller melt pools. Typical LPBF range: 200–2000 mm/s.',
  },
  {
    key: 'absorptivity',
    label: 'Absorptivity',
    symbol: 'η',
    unit: '',
    min: 0.1,
    max: 0.8,
    step: 0.01,
    defaultValue: 0.35,
    tooltip:
      'Fraction of laser energy absorbed by the powder bed (0–1). Depends on material, powder morphology, and laser wavelength. Metals range from 0.1 (aluminum) to 0.5+ (titanium).',
  },
  {
    key: 'conductivity',
    label: 'Thermal Conductivity',
    symbol: 'k',
    unit: 'W/m·K',
    min: 5,
    max: 200,
    step: 0.5,
    defaultValue: 18,
    tooltip:
      'How efficiently the material conducts heat away from the melt pool. Higher conductivity → faster heat dissipation → smaller melt pool. Typical range: 6 (Ti) to 200 (Al).',
  },
  {
    key: 'diffusivity',
    label: 'Thermal Diffusivity',
    symbol: 'α',
    unit: 'mm²/s',
    min: 1,
    max: 80,
    step: 0.1,
    defaultValue: 5.2,
    tooltip:
      'Rate at which heat spreads through the material (α = k/ρcₚ). Combines conductivity, density, and heat capacity into one number. Higher → heat diffuses faster.',
  },
  {
    key: 'liquidus',
    label: 'Liquidus Temperature',
    symbol: 'T_liq',
    unit: '°C',
    min: 400,
    max: 1700,
    step: 10,
    defaultValue: 1650,
    tooltip:
      'Temperature at which the material is fully molten. Points above this threshold form the melt pool. Ti-6Al-4V: 1655°C · 316L SS: 1400°C · AlSi10Mg: 596°C.',
  },
  {
    key: 'preheat',
    label: 'Preheat Temperature',
    symbol: 'T₀',
    unit: '°C',
    min: 20,
    max: 500,
    step: 5,
    defaultValue: 25,
    tooltip:
      'Starting temperature of the powder bed before the laser passes. Preheating reduces thermal gradients and residual stress. Some systems preheat to 100–200°C.',
  },
]
